# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Symbolic Execution: Foundations, Techniques, Applications and Future Perspectives"
author: Dominic Steinhöfel
logo: logo.png # TODO

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 100

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

launch_buttons:
  binderhub_url: ""

# Information about where the book exists on the web
repository:
  url: https://github.com/rindPHI/se-book-festschrift-rh  # Online location of your book
  #path_to_book: jupyter-book/book  # Optional path to your book, relative to the repository root
  branch: ghpages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
